apiVersion: v1
kind: Service
metadata:
  name: demo-web-svc
  namespace: demo
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: demo-web
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
