apiVersion: v1
kind: Service
metadata:
  name: demo-web
  namespace: demo
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: demo-web
  ports:
  - port: 8080
    targetPort: 80
